version: 2

refs:
  container: &container
    docker:
      - image: circleci/node:8.15@sha256:dc1314f3d6e33f8baf7f4ff73a3bee6be4be133143fb1c4635aad8b262e81203
    working_directory: ~/repo

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Post to GitHub
          command: npx ci-scripts github-post
      - run:
          name: Post to Slack
          command: npx ci-scripts slack

  master:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Post to GitHub
          command: npx ci-scripts github-post
      - run:
          name: Post to Slack
          command: npx ci-scripts slack
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  all:
    jobs:
      - all:
          context: common-env-vars
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          context: common-env-vars
          filters:
            branches:
              only: master
